"""Revenue model (§20): expected revenue generated by the credit product,
per customer-snapshot.

```
Interest Revenue = Average Balance × APR / 12   (APR is annual, so /12
                                                   for a monthly figure)
Interchange       = Monthly Spend × Interchange Rate
Late Fees         = late_fee_amount if days_past_due > 0 else 0
```

FX fees (§20's other optional example) are deliberately NOT modeled: the
generated transaction data is 100% EUR (checked directly against
transactions.csv), so there's no real signal to build one from -- adding
one would be fabricating a number with no basis in the data. Other
Product Fees aren't modeled either, for the same reason: nothing in the
generated data represents them.

**This is the exact formula Phase 1's label generator already used** to
build `future_interest_revenue`/`future_interchange_revenue`
(`labels.py`) -- not a coincidence, a deliberate reuse, so this module's
correctness can be verified against real generated numbers rather than
just asserted: `validate_against_labels()` reconstructs each snapshot
cohort's future_interest_revenue/future_interchange_revenue directly from
the raw monthly table at the labeled future month and confirms an exact
match (up to the 2-decimal rounding labels.csv itself applies).

Computed at the CURRENT snapshot (not the future window) for every
customer, since Phase 5's optimization needs to evaluate revenue at
CANDIDATE credit limits, not just replay history.

Run: python -m credit_limit_optimizer.models.revenue_model
"""

from __future__ import annotations

import json

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from credit_limit_optimizer.models.expected_loss import load_full_feature_table
from credit_limit_optimizer.models.risk_model import split_cohorts
from credit_limit_optimizer.utils.config import PROJECT_ROOT, load_config
from credit_limit_optimizer.utils.logging import get_logger

log = get_logger("revenue_model")

FIG_DIR = PROJECT_ROOT / "reports" / "figures" / "revenue"
REPORT_PATH = PROJECT_ROOT / "reports" / "outputs" / "revenue_report.json"
MODEL_CARD_PATH = PROJECT_ROOT / "reports" / "model_cards" / "revenue_model.md"

RAW_DIR = PROJECT_ROOT / "data" / "raw"

plt.rcParams.update({
    "figure.dpi": 110, "axes.grid": True, "grid.alpha": 0.3,
    "axes.spines.top": False, "axes.spines.right": False,
})


def compute_revenue(df: pd.DataFrame, config: dict) -> pd.DataFrame:
    econ = config["economics"]
    interest = df["average_balance"] * df["apr"] / 12
    interchange = df["monthly_spend"] * econ["interchange_rate"]
    late_fee = np.where(df["days_past_due"] > 0, econ["late_fee_amount"], 0.0)
    total = interest + interchange + late_fee
    return pd.DataFrame({
        "interest_revenue": interest, "interchange_revenue": interchange,
        "late_fee_revenue": late_fee, "total_revenue": total,
    }, index=df.index)


def validate_against_labels(config: dict) -> dict:
    """Recomputes future_interest_revenue/future_interchange_revenue
    directly from the raw monthly table at each label's own future month,
    using this module's exact formula, and compares to labels.csv's real
    (already-generated) values -- a genuine correctness check against
    real data, not a self-fulfilling assertion."""
    labels = pd.read_csv(RAW_DIR / "labels.csv")
    monthly = pd.read_csv(RAW_DIR / "monthly_customer_behavior.csv")
    monthly = monthly.sort_values(["customer_id", "month"]).reset_index(drop=True)
    monthly["month_index"] = monthly.groupby("customer_id").cumcount() + 1
    accounts = pd.read_csv(PROJECT_ROOT / "data" / "processed" / "credit_accounts.csv")[["customer_id", "apr"]]

    horizon = config["snapshots"]["horizon_months"]
    n_months = int(monthly["month_index"].max())
    labels = labels.copy()
    labels["future_month_index"] = (labels["snapshot_month"] + horizon).clip(upper=n_months)

    merged = labels.merge(
        monthly[["customer_id", "month_index", "average_balance", "monthly_spend"]],
        left_on=["customer_id", "future_month_index"], right_on=["customer_id", "month_index"],
    ).merge(accounts, on="customer_id")

    implied_interest = (merged["average_balance"] * merged["apr"] / 12).round(2)
    implied_interchange = (merged["monthly_spend"] * config["economics"]["interchange_rate"]).round(2)
    interest_diff = (implied_interest - merged["future_interest_revenue"]).abs()
    interchange_diff = (implied_interchange - merged["future_interchange_revenue"]).abs()

    return {
        "n_checked": int(len(merged)),
        "max_abs_diff_interest": float(interest_diff.max()),
        "mean_abs_diff_interest": float(interest_diff.mean()),
        "max_abs_diff_interchange": float(interchange_diff.max()),
        "mean_abs_diff_interchange": float(interchange_diff.mean()),
    }


def plot_revenue_distribution(revenue: pd.DataFrame) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.hist(revenue["total_revenue"], bins=60, color="#1565C0")
    ax.set_xlabel("Monthly revenue (EUR)")
    ax.set_ylabel("Customer-snapshots")
    ax.set_title("Total monthly revenue distribution (test cohort)")
    fig.savefig(FIG_DIR / "01_revenue_distribution.png", bbox_inches="tight")
    plt.close(fig)


def plot_revenue_by_segment(by_segment: pd.DataFrame) -> None:
    segments = ["prime", "near_prime", "subprime"]
    components = ["interest_revenue", "interchange_revenue", "late_fee_revenue"]
    colors = ["#1565C0", "#F9A825", "#C62828"]
    fig, ax = plt.subplots(figsize=(7, 4.5))
    bottom = np.zeros(len(segments))
    for comp, color in zip(components, colors):
        values = by_segment.loc[segments, comp].to_numpy()
        ax.bar(segments, values, bottom=bottom, label=comp.replace("_", " "), color=color)
        bottom += values
    ax.set_ylabel("Mean monthly revenue (EUR)")
    ax.set_title("Mean monthly revenue by segment, by component (test cohort)")
    ax.legend()
    fig.savefig(FIG_DIR / "02_revenue_by_segment.png", bbox_inches="tight")
    plt.close(fig)


def run_revenue_model() -> dict:
    config = load_config()
    df = load_full_feature_table()
    cohorts = split_cohorts(df)
    test = cohorts["test"]

    n_before = len(test)
    test = test.dropna(subset=["average_balance", "apr", "monthly_spend", "days_past_due"])
    n_excluded = n_before - len(test)
    log.info("Excluding %d of %d test rows (missing revenue inputs)", n_excluded, n_before)

    revenue = compute_revenue(test, config)
    log.info(
        "Test cohort mean monthly revenue: interest=€%.2f interchange=€%.2f late_fee=€%.2f total=€%.2f",
        revenue["interest_revenue"].mean(), revenue["interchange_revenue"].mean(),
        revenue["late_fee_revenue"].mean(), revenue["total_revenue"].mean(),
    )

    FIG_DIR.mkdir(parents=True, exist_ok=True)
    plot_revenue_distribution(revenue)

    by_segment = revenue.join(test["customer_segment"]).groupby("customer_segment")[
        ["interest_revenue", "interchange_revenue", "late_fee_revenue", "total_revenue"]
    ].mean()
    plot_revenue_by_segment(by_segment)
    log.info("Mean total revenue by segment: %s", by_segment["total_revenue"].round(2).to_dict())

    validation = validate_against_labels(config)
    log.info(
        "Formula validated against %d real labels: max|diff| interest=€%.4f interchange=€%.4f",
        validation["n_checked"], validation["max_abs_diff_interest"], validation["max_abs_diff_interchange"],
    )

    report = {
        "n_test_rows": int(len(test)), "n_excluded_missing_inputs": n_excluded,
        "mean_revenue": {
            "interest_revenue": float(revenue["interest_revenue"].mean()),
            "interchange_revenue": float(revenue["interchange_revenue"].mean()),
            "late_fee_revenue": float(revenue["late_fee_revenue"].mean()),
            "total_revenue": float(revenue["total_revenue"].mean()),
        },
        "total_portfolio_monthly_revenue": float(revenue["total_revenue"].sum()),
        "by_segment": by_segment.round(4).to_dict(orient="index"),
        "formula_validation_against_real_labels": validation,
        "late_fee_amount": config["economics"]["late_fee_amount"],
        "interchange_rate": config["economics"]["interchange_rate"],
    }
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with REPORT_PATH.open("w") as f:
        json.dump(report, f, indent=2, default=str)
    log.info("Wrote %s", REPORT_PATH.relative_to(PROJECT_ROOT))

    write_model_card(report)
    log.info("Wrote %s", MODEL_CARD_PATH.relative_to(PROJECT_ROOT))
    return report


def write_model_card(report: dict) -> None:
    mr = report["mean_revenue"]
    v = report["formula_validation_against_real_labels"]
    lines = [
        "# Model Card — Revenue Model (§20)",
        "",
        "Interest Revenue = Average Balance × APR / 12; Interchange = Monthly Spend × "
        f"{report['interchange_rate']:.1%}; Late Fee = €{report['late_fee_amount']} in any "
        "month with days_past_due > 0. FX fees and other product fees are not modeled — "
        "the generated data is 100% EUR with no basis for either.",
        "",
        "## Formula validation against real generated data",
        "",
        f"This module's exact formula, applied to the raw monthly table at each label's own "
        f"future month, reconstructs labels.csv's `future_interest_revenue`/"
        f"`future_interchange_revenue` (independently generated by Phase 1's simulation) to "
        f"within €{max(v['max_abs_diff_interest'], v['max_abs_diff_interchange']):.2f} across "
        f"{v['n_checked']:,} labeled rows — i.e. exactly, up to labels.csv's own 2-decimal "
        "rounding. This isn't a coincidence: it's the same formula Phase 1 used to generate "
        "those labels, confirmed to match rather than just asserted.",
        "",
        "## Expected monthly revenue (test cohort, current snapshot)",
        "",
        f"{report['n_excluded_missing_inputs']:,} of "
        f"{report['n_test_rows'] + report['n_excluded_missing_inputs']:,} test rows excluded "
        "(missing one of average_balance/apr/monthly_spend/days_past_due — real Phase 1 "
        "data-quality artifacts, same pattern as the Expected Loss piece).",
        "",
        f"Mean per customer-snapshot: interest €{mr['interest_revenue']:.2f}, interchange "
        f"€{mr['interchange_revenue']:.2f}, late fees €{mr['late_fee_revenue']:.2f}, "
        f"**total €{mr['total_revenue']:.2f}**. Total portfolio monthly revenue on the "
        f"{report['n_test_rows']:,}-row test cohort: €{report['total_portfolio_monthly_revenue']:,.0f}.",
        "",
        "![revenue distribution](../figures/revenue/01_revenue_distribution.png)",
        "",
        "## Revenue by segment",
        "",
    ]
    for seg in ["prime", "near_prime", "subprime"]:
        row = report["by_segment"][seg]
        lines.append(
            f"- **{seg}**: interest €{row['interest_revenue']:.2f}, interchange "
            f"€{row['interchange_revenue']:.2f}, late fees €{row['late_fee_revenue']:.2f}, "
            f"total €{row['total_revenue']:.2f}"
        )
    lines += [
        "",
        "![revenue by segment](../figures/revenue/02_revenue_by_segment.png)",
        "",
    ]
    el_report_path = PROJECT_ROOT / "reports" / "outputs" / "expected_loss_report.json"
    if el_report_path.exists():
        with el_report_path.open() as f:
            el_report = json.load(f)
        lines += ["## Preview: revenue vs. Expected Loss by segment", ""]
        for seg in ["prime", "near_prime", "subprime"]:
            annual_revenue = report["by_segment"][seg]["total_revenue"] * 12
            el = el_report["el_by_segment"][seg]
            lines.append(f"- **{seg}**: €{annual_revenue:,.2f}/year revenue − €{el:,.2f} Expected Loss = €{annual_revenue - el:,.2f} net")
        lines += [
            "",
            "Funding cost and operational cost (not yet subtracted here) still apply to all "
            "three; full Customer Profitability (§22) is the next piece.",
            "",
        ]
    MODEL_CARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    with MODEL_CARD_PATH.open("w") as f:
        f.write("\n".join(lines))


def main() -> None:
    run_revenue_model()


if __name__ == "__main__":
    main()
